event_dict = {'美食/正餐': '美食/正餐[Regular Cuisine]',
'美食/地方菜': '美食/地方菜[Local Cuisine]',
'美食/火锅': '美食/火锅[HotPot]',
'美食/烧烤': '美食/烧烤[Barbecue]',
'美食/西餐': '美食/西餐[Western Cuisine]',
'美食/外国菜': '美食/外国菜[Foreign Cuisine]',
'美食/下午茶': '美食/下午茶[Tea Time]',
'美食/咖啡': '美食/咖啡[Coffee]',
'美食/小吃': '美食/小吃[Snacks]',
'美食/宵夜': '美食/宵夜[Late-night snacks]',
'美食/农家乐': '美食/农家乐[Nongjiale]',
'美食/家常菜': '美食/家常菜[Home Cooking]',
'休闲娱乐/按摩': '休闲娱乐/按摩[Massage]',
'休闲娱乐/足疗': '休闲娱乐/足疗[foot massage]',
'休闲娱乐/洗浴': '休闲娱乐/洗浴[Bath]',
'休闲娱乐/汗蒸': '休闲娱乐/汗蒸[Steam]',
'休闲娱乐/唱歌': '休闲娱乐/唱歌[Singing]',
'休闲娱乐/喝茶': '休闲娱乐/喝茶[Tea]',
'休闲娱乐/桌游': '休闲娱乐/桌游[Table games]',
'休闲娱乐/酒吧': '休闲娱乐/酒吧[Bars]',
'休闲娱乐/密室逃脱': '休闲娱乐/密室逃脱[Escape Room]',
'休闲娱乐/DIY手工': '休闲娱乐/DIY手工[DIY Crafts]',
'休闲娱乐/游乐': '休闲娱乐/游乐[Amusement]',
'休闲娱乐/采摘': '休闲娱乐/采摘[Picking]',
'休闲娱乐/野餐': '休闲娱乐/野餐[Picnic]',
'休闲娱乐/聚会': '休闲娱乐/聚会[Party]',
'演出电影/演唱会': '演出电影/演唱会[Concerts]',
'演出电影/音乐节': '演出电影/音乐节[Music Festivals]',
'演出电影/音乐会': '演出电影/音乐会[Concerts]',
'演出电影/歌剧': '演出电影/歌剧[Opera]',
'演出电影/艺术活动': '演出电影/艺术活动[Artistic events]',
'演出电影/电影': '演出电影/电影[Movies]',
'工作/出差': '工作/出差[Business trips]',
'工作/会议': '工作/会议[Meetings and Conferences]',
'工作/团建': '工作/团建[Reunion]',
'购物/逛街': '购物/逛街[Shopping]',
'购物/网购': '购物/网购[Online shopping]',
'运动健身/飞盘': '运动健身/飞盘[Frisbee]',
'运动健身/游泳': '运动健身/游泳[Swimming]',
'运动健身/羽毛球': '运动健身/羽毛球[Badminton]',
'运动健身/溜冰': '运动健身/溜冰[Ice skating]',
'运动健身/滑冰': '运动健身/滑冰[Skating]',
'运动健身/射击': '运动健身/射击[Shooting]',
'运动健身/射箭': '运动健身/射箭[Archery]',
'运动健身/篮球': '运动健身/篮球[Basketball]',
'运动健身/桌球': '运动健身/桌球[Billiards]',
'运动健身/网球': '运动健身/网球[Tennis]',
'运动健身/攀岩': '运动健身/攀岩[Rock Climbing]',
'运动健身/乒乓球': '运动健身/乒乓球[Table tennis]',
'运动健身/足球': '运动健身/足球[Soccer]',
'运动健身/高尔夫球': '运动健身/高尔夫球[Golf]',
'运动健身/保龄球': '运动健身/保龄球[Bowling]',
'运动健身/壁球': '运动健身/壁球[Squash]',
'运动健身/跆拳道': '运动健身/跆拳道[Taekwondo]',
'运动健身/柔道': '运动健身/柔道[Judo]',
'运动健身/泰拳': '运动健身/泰拳[Muay Thai]',
'运动健身/拳击': '运动健身/拳击[Boxing]',
'运动健身/自行车': '运动健身/自行车[Cycling]',
'运动健身/跑步': '运动健身/跑步[Running]',
'运动健身/滑雪': '运动健身/滑雪[Skiing]',
'学习培训/外语': '学习培训/外语[Foreign Languages]',
'学习培训/音乐': '学习培训/音乐[Music]',
'学习培训/舞蹈': '学习培训/舞蹈[Dance]',
'学习培训/书法': '学习培训/书法[Calligraphy]',
'学习培训/学科辅导': '学习培训/学科辅导[Academic Counseling]',
'学习培训/驾校': '学习培训/驾校[Driving School]',
'生活/家政': '生活/家政[Home Economics]',
'生活/政府': '生活/政府[Government affairs]',
'生活/影印': '生活/影印[Photocopying]',
'生活/约会': '生活/约会[Date]',
'生活/旅游': '生活/旅游[Travel]',
'生活/外出游玩': '生活/外出游玩[Outing]',
'生活/酒店': '生活/酒店[Hotels]',
'生活/租房': '生活/租房[Renting a room]',
'出行/飞机': '出行/飞机[Airplanes]',
'出行/公共汽车': '出行/公共汽车[Buses]',
'出行/私家车出行': '出行/私家车出行[Private Car Travel]',
'休闲娱乐/棋牌': '休闲娱乐/棋牌[Chess]',
'美食/甜点': '美食/甜点[dessert]',
'工作/应酬': '工作/应酬[socializing]',
'汽车/罚单': '汽车/罚单[violation ticket]',
'休闲娱乐/网吧': '休闲娱乐/网吧[Internet cafe]',
'演出电影/话剧': '演出电影/话剧[drama]',
'工作/培训': '工作/培训[training]',
'工作/项目': '工作/项目[project]',
'工作/邮件': '工作/邮件[mail]',
'汽车/买车': '汽车/买车[buy a car]',
'汽车/保险': '汽车/保险[insurance]',
'汽车/修车': '汽车/修车[Car Repair]',
'汽车/汽车美容': '汽车/汽车美容[Car Detailing]',
'汽车/洗车': '汽车/洗车[Car Wash]',
'运动健身/健身': '运动健身/健身[Fitness]',
'汽车/年检': '汽车/年检[Annual Inspection]',
'运动健身/冰球': '运动健身/冰球[Hockey]',
'运动健身/马拉松': '运动健身/马拉松[Marathon]',
'医疗/看望病人': '医疗/看望病人[Visiting patients]',
'学习培训/美术': '学习培训/美术[Fine Arts]',
'医疗/体检': '医疗/体检[Physical examination]',
'医疗/买药': '医疗/买药[buying medicine]',
'生活/取钱': '生活/取钱[withdrawing money]',
'生活/存钱': '生活/存钱[Deposit money]',
'生活/洗衣': '生活/洗衣[Laundry]',
'生活/维修': '生活/维修[Repair]',
'生活/缴费': '生活/缴费[Paying bills]',
'生活/结婚': '生活/结婚[Marriage]',
'生活/买票': '生活/买票[Buy Ticket]',
'出行/高铁/火车': '出行/高铁/火车[High-speed rail/train]',
'出行/船渡': '出行/船渡[Ferry]'
}

rel_dict = {
'基本属性-姓名': '基本属性-姓名\nName',
'基本属性-昵称': '基本属性-昵称\nNickname',
'基本属性-性别': '基本属性-性别\nGender',
'基本属性-年龄': '基本属性-年龄\nAge',
'基本属性-身份证号': '基本属性-身份证号\nID number',
'基本属性-银行卡号': '基本属性-银行卡号\nBank Card Number',
'基本属性-国籍': '基本属性-国籍\nNationality',
'联系方式-电话号码': '联系方式-电话号码\nPhone Number',
'联系方式-电子邮箱': '联系方式-电子邮箱\nE-Mail',
'住址-家庭地址': '住址-家庭地址\nHome Address',
'住址-公司地址': '住址-公司地址\nCompany Address',
'出生-出生地': '出生-出生地\nPlace of Birth',
'出生-生日': '出生-生日\nBirthday',
'教育背景-学历': '教育背景-学历\nEducation',
'教育背景-学校名称': '教育背景-学校名称\nSchool Name',
'教育背景-入学时间': '教育背景-入学时间\nEnrollment time',
'教育背景-毕业时间': '教育背景-毕业时间\nGraduation time',
'教育背景-专业名称': '教育背景-专业名称\nMajor',
'政治面貌': '政治面貌\nPolitical Appearance',
'生理特征-身高': '生理特征-身高\nHeight',
'生理特征-体重': '生理特征-体重\nWeight',
'性格类型': '性格类型\nPersonality type',
'工作背景-工作开始时间': '工作背景-工作开始时间\nWork start time',
'工作背景-工作结束时间': '工作背景-工作结束时间\nWork end time',
'工作背景-工作单位': '工作背景-工作单位\nWork Organization',
'工作背景-工作职务': '工作背景-工作职务\nJob Title',
'工作背景-工作薪资': '工作背景-工作薪资\nSalary',
'婚姻情况': '婚姻情况\nMarital Status',
'个人偏好-电影偏好': '个人偏好-电影偏好\nMovie Preference',
'个人偏好-菜品偏好': '个人偏好-菜品偏好\nCuisine Preference',
'个人偏好-音乐偏好': '个人偏好-音乐偏好\nMusic Preference',
'个人偏好-购物偏好': '个人偏好-购物偏好\nShopping Preferences',
'个人偏好-景点偏好': '个人偏好-景点偏好\nAttractions Preference',
'个人偏好-酒店偏好': '个人偏好-酒店偏好\nHotel Preferences'
}

attr_dict = {'同学-幼儿园同学': '同学-幼儿园同学\nKindergarten Classmate',
'同学-小学同学': '同学-小学同学\nElementary School Classmate',
'同学-初中同学': '同学-初中同学\nJunior High School Classmate',
'同学-高中同学': '同学-高中同学\nHigh School Classmate',
'同学-大学同学': '同学-大学同学\nUniversity Classmate',
'同学-研究生同学': '同学-研究生同学\nPostgraduate Classmate',
'同事-前同事': '同事-前同事\nFormer Colleagues',
'同事-上级同事': '同事-上级同事\nSuperior Colleagues',
'同事-平级同事': '同事-平级同事\nEquivalent Colleagues',
'同事-下级同事': '同事-下级同事\nLower-level Colleagues',
'合作伙伴-甲方/乙方领导': '合作伙伴-甲方/乙方领导\nLeader of Party A / Party B',
'合作伙伴-客户': '合作伙伴-客户\nCustomer',
'合作伙伴-顾问': '合作伙伴-顾问\nConsultant',
'合作伙伴-中介': '合作伙伴-中介\nIntermediary',
'合作伙伴-子女老师': '合作伙伴-子女老师\nChild Teacher',
'合作伙伴-合伙人': '合作伙伴-合伙人\nPartner',
'合作伙伴-房东': '合作伙伴-房东\nLandlord',
'合作伙伴-租客': '合作伙伴-租客\nTenant',
'家人-父亲': '家人-父亲\nFather',
'家人-母亲': '家人-母亲\nMother',
'家人-兄弟': '家人-兄弟\nBrother',
'家人-姊妹': '家人-姊妹\nSister',
'家人-儿子': '家人-儿子\nSons',
'家人-女儿': '家人-女儿\nDaughter',
'家人-配偶': '家人-配偶\nSpouse',
'家人-旁系亲属': '家人-旁系亲属\ncollateral relatives',
'家人-爷爷': '家人-爷爷\nGrandfather',
'家人-奶奶': '家人-奶奶\nGrandma',
'家人-外公': '家人-外公\nGrandpa',
'家人-外婆': '家人-外婆\nGrandmother',
'婚亲关系-岳父': '婚亲关系-岳父\nFather-in-law',
'婚亲关系-岳母': '婚亲关系-岳母\nmother-in-law',
'婚亲关系-公公': '婚亲关系-公公\nfather-in-law',
'婚亲关系-婆婆': '婚亲关系-婆婆\nmother-in-law',
'婚亲关系-亲家': '婚亲关系-亲家\nin-laws',
'婚亲关系-小姨子': '婚亲关系-小姨子\nsister-in-law',
'婚亲关系-小叔子': '婚亲关系-小叔子\nbrother-in-law',
'婚亲关系-儿媳': '婚亲关系-儿媳\ndaughter-in-law',
'婚亲关系-女婿': '婚亲关系-女婿\nson-in-law',
'法定关系-监护人': '法定关系-监护人\nguardian',
'法定关系-被监护人': '法定关系-被监护人\nWard',
'法定关系-继承人': '法定关系-继承人\nHeir',
'法定关系-被继承人': '法定关系-被继承人\nDeceased',
'法定关系-养父': '法定关系-养父\nAdoptive father',
'法定关系-养母': '法定关系-养母\nAdoptive mother',
'法定关系-养子': '法定关系-养子\nAdopted son',
'法定关系-养女': '法定关系-养女\nAdopted Daughter',
'法定关系-继父': '法定关系-继父\nStepfather',
'法定关系-继母': '法定关系-继母\nstepmother',
'法定关系-继子': '法定关系-继子\nstepson',
'法定关系-继女': '法定关系-继女\nStepdaughter',
'恋人-前恋人': '恋人-前恋人\nEx-lover',
'恋人-现恋人': '恋人-现恋人\ncurrent lover',
'朋友-密友': '朋友-密友\nclose friend',
'朋友-好友': '朋友-好友\nbest friend',
'朋友-日常朋友': '朋友-日常朋友\nEveryday friends',
'朋友-熟人': '朋友-熟人\nAcquaintances',
'朋友-距离朋友': '朋友-距离朋友\nDistance Friends',
'朋友-网友': '朋友-网友\nInternet friends',
'教师-学校老师': '教师-学校老师\nSchool Teacher',
'教师-辅导班老师': '教师-辅导班老师\nTutor',
'教师-大学导师': '教师-大学导师\nCollege tutor',
'学生-前学生': '学生-前学生\nFormer student',
'学生-现学生': '学生-现学生\nCurrent Student'
}
